Bug fix for adding a link
latos/editor pull request #17
Opened 2017-08-03 01:56 UTC by michaelnamlee

2017-08-09 10:43 UTC, blambo requested changes

2017-08-09 10:43 UTC, blambo commented on src/selection.js
> +      var result = false;
Why are we renaming this from a more specific to less specific variable name?

2017-08-09 10:43 UTC, blambo commented on src/selection.js
> +  me.getParentElement = function() {
This seems to assume that the selection is all within a single parent, what if the selection is like:
`<p><b>12[34</b>as]df</p>`
Should the parent element be the `<b>` element or the `<p>`?

2017-08-09 10:43 UTC, blambo commented on src/toolbar.js
> +          selection.getParentElement().target = '_blank';
This makes an assumption about where our selection is after the `execCommand` that I don't think we can necessarily make.

2017-08-10 01:31 UTC, michaelnamlee commented on src/selection.js
> +      var result = false;
because `within` only makes sense when we were finding whether an element was within another

2017-08-10 06:22 UTC, blambo approved these changes

2017-08-10 06:23 UTC, merged